### PR TITLE
Update imports to work with novaclient 3.4.0

### PR DESCRIPTION
**Pull request by jasondunsmore**

### CODE REVIEW

**Comment by coderanger** [comment]
As with https://github.com/rackerlabs/ip_associations_python_novaclient_ext/pull/2, could keep compat if needed.

**Comment by jtwebman** [comment]
IS this ever going to get merged? The client is on 4.0 now and this is still broken. Took me hours to find it and make the correct fix.

**Comment by rphillips** [comment]
+1 needs a merge

**Comment by roaet** [comment]
Fixed this in #14. Same code, just fixed flake8 errors.

**Comment by jimrollenhagen** [comment]
Fixed in #14

**Pull request closed without merging**
